### PR TITLE
Add preference listener to change processor without restart

### PR DESCRIPTION
**Pull request by bwiernik**
@fbennett Finally got this working. Sorry to get it just after you pushed a release.

### CODE REVIEW

**Comment by bwiernik** [comment]
@fbennett Just a nudge.

**Comment by fbennett** [comment]
Merged the code and attempted a release. The Firefox signing API seems to be on holiday this evening, I'll try again in the morning.

**Comment by bwiernik** [comment]
No worries. Thanks!

**Comment by fbennett** [comment]
I take that back -- it timed out on the first attempt, but the second try just went through. It should be up and ready as Propachi-vanilla v.1.1.109.

**Pull request merged**
