### PR TITLE
Begin merging vanilla and uppercase versions

### PR DESCRIPTION
**Pull request by bwiernik**
I've started the work to merge the vanilla and uppercase versions of propachi (Addresses #1)

This PR changes:
- Build two versions of the processors (citeprocVanilla and citeprocUppercase) in build.sh
- Add functions to `bootstrap.js` to choose which version of citeproc to inject
- Add a preference pane to toggle `extensions.propachi.uppercase` preference

Remaining to do:
- Add preference listener to monitor changes in preference and re-initialize the CSL processor on change
- Rename to propachi and clean up references in build.sh, install.rdf, etc.

Currently, changing the setting requires a restart of Zotero. I wasn't able to get any preference listener code to work to change which citeproc version was injected without a Zotero restart. @fbennett Do you know the best way to make that happen?

### CODE REVIEW

**Comment by bwiernik** [comment]
@fbennett Just pinging your attention on this.

**Comment by fbennett** [comment]
@bwiernik: Much apology for the time it has taken me to turn to your work on this. Tested it, and it works great! Two things.
1. I'll add a little note in the options.xul to say that a change takes effect after restart; and
2. Would it be okay to add your name as co-creator?

**Comment by bwiernik** [comment]
Sure, that would be great!

**Comment by fbennett** [comment]
On its way then.

**Comment by fbennett** [comment]
Should all be set now. I've tried setting the update target for propachi-upper to the propachi-vanilla image, we'll see if that works. Apart from that, the plugin is up (under the propachi-vanilla link), and I've edited the Juris-M downloads page to list only the one plugin.

Thanks a lot for this, it simplifies the picture immensely.

**Comment by bwiernik** [comment]
Glad to help!

**Comment by bwiernik** [comment]
I did get a preference listener for restartless changing of the preferences working.

**Pull request merged**
